DROP DATABASE SweetPixelsStudio;

CREATE DATABASE SweetPixelsStudio;
USE SweetPixelsStudio;

# CREATE TABLES
# Create CUSTOMER table (contains all information with regards to Sweet Pixels Studio's customers.)
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
CUST_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR (50) NOT NULL,
LAST_NAME VARCHAR (50) NOT NULL,
CONTACT_NUMBER VARCHAR (15),
EMAIL VARCHAR (100),
STREET VARCHAR (100),
CITY VARCHAR (100),
POSTAL_CODE VARCHAR (10),
DATE_CREATED DATE DEFAULT (CURRENT_DATE)
);
# Build data for CUSTOMER
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Emily', 'Thompson', '519-555-0101', 'emily.thompson@example.com', '125 Maple Grove Drive', 'Windsor', 'N8X 2L4');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Liam', 'Anderson', '226-555-0102', 'liam.anderson@example.com', '48 Riverside Lane', 'Tecumseh', 'N8N 3K7');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Sophia', 'Martin', '519-555-0103', 'sophia.martin@example.com', '217 Cedar Hill Road', 'LaSalle', 'N9H 4P2');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Noah', 'Wilson', '226-555-0104', 'noah.wilson@example.com', '63 Lakeside Crescent', 'Lakeshore', 'N8L 1B6');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Olivia', 'Bennett', '519-555-0105', 'olivia.bennett@example.com', '91 Riverbend Street', 'Amherstburg', 'N9V 2K8');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Ethan', 'Clark', '226-555-0106', 'ethan.clark@example.com', '35 Countyview Avenue', 'Essex', 'N8M 2R5');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Ava', 'Robinson', '519-555-0107', 'ava.robinson@example.com', '142 Gardenview Road', 'Kingsville', 'N9Y 3L7');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Mason', 'Carter', '226-555-0108', 'mason.carter@example.com', '76 Greenhouse Lane', 'Leamington', 'N8H 4C3');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Isabella', 'Cooper', '519-555-0109', 'isabella.cooper@example.com', '204 Riverside Drive', 'Windsor', 'N9A 5T2');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,CONTACT_NUMBER,EMAIL, STREET, CITY, POSTAL_CODE)
 VALUES ('Lucas', 'Mitchell', '226-555-0110', 'lucas.mitchell@example.com', '58 Sunset Crescent', 'Tecumseh', 'N8V 2M9');
# Check CUSTOMER table
SELECT *
FROM CUSTOMER;




# Create ORDERS table (contains all information with regards to Sweet Pixels Studio's orders.)
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS
(
ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_DATE DATE DEFAULT (CURRENT_DATE),
BOOKING_DATE DATE,
CUST_ID INT,
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);
# Build data for ORDERS
INSERT INTO ORDERS (BOOKING_DATE, CUST_ID)
VALUES ('2026-09-01', 1);
INSERT INTO ORDERS (BOOKING_DATE, CUST_ID)
VALUES ('2026-09-10', 5);
INSERT INTO ORDERS (BOOKING_DATE, CUST_ID)
VALUES ('2026-09-14', 7);
# Check ORDERS table
SELECT *
FROM ORDERS;





# Create SERVICES table (contains all information with regards to Sweet Pixels Studio's list of service types.)
DROP TABLE IF EXISTS SERVICES;
CREATE TABLE SERVICES
(
SERVICE_TYPE VARCHAR (2) PRIMARY KEY,
SERVICE_NAME VARCHAR (50)
);
# Build data for SERVICES
INSERT INTO SERVICES VALUES ('PH', 'Photography');
INSERT INTO SERVICES VALUES ('CP', 'Custom Products');
# Check SERVICES table
SELECT *
FROM SERVICES;





# Create CUSTOM_PRODUCTS table (contains all information with regards to Sweet Pixels Studio's list of custom products offered.)
DROP TABLE IF EXISTS CUSTOM_PRODUCTS;
CREATE TABLE CUSTOM_PRODUCTS
(
SERVICE_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
DATE_CREATED DATE DEFAULT (CURRENT_DATE),
CATEGORY VARCHAR (30) NOT NULL,
NAME VARCHAR (50) NOT NULL,
SERVICE_ID VARCHAR (6) UNIQUE,
DESCRIPTION VARCHAR (50),
BASE_PRICE DECIMAL (10,2),
SERVICE_TYPE VARCHAR (2),
FOREIGN KEY (SERVICE_TYPE) REFERENCES SERVICES(SERVICE_TYPE)
);
# Build data for CUSTOM_PRODUCTS
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Party', 'Fridge Magnets', 'PAFMRD', '2" Round', 0.5, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Party', 'Fridge Magnets', 'PAFMSQ', '3" Square', 1.5, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Party', 'Fridge Magnets', 'PAFMRC', '2x3" Rectangle', 2, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Party', 'Custom Stickers', 'PACS11','8x11', 3, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Party', 'Custom Packaging', 'PACPSM', 'Small', 1, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Party', 'Custom Packaging', 'PACPMD', 'Medium', 5, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Party', 'Custom Packaging', 'PACPLG', 'Large', 10, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Prints', 'Small Prints', 'PRSP46', '4x6', 0.5, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Prints', 'Small Prints', 'PRSP57', '5x7', 1, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Prints', 'Small Prints', 'PRSP81', '8x10', 1.5, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Album', 'Mini', 'ALMI08', '8x8', 30, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Album', 'Standard', 'ALST10', '10x10', 70, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Album', 'Large', 'ALLG12', '12x12', 180, 'CP');
INSERT INTO CUSTOM_PRODUCTS (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, BASE_PRICE, SERVICE_TYPE)
VALUES ('Album', 'Case', 'ALCS00', 'Custom Album Case', 100, 'CP');
# Check CUSTOM_PRODUCTS table
SELECT *
FROM CUSTOM_PRODUCTS;





# Create PHOTOGRAPHY table (contains all information with regards to Sweet Pixels Studio's list of photography  offered.)
DROP TABLE IF EXISTS PHOTOGRAPHY;
CREATE TABLE PHOTOGRAPHY
(
SERVICE_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
DATE_CREATED DATE DEFAULT (CURRENT_DATE),
CATEGORY VARCHAR (30) NOT NULL,
NAME VARCHAR (50) NOT NULL,
SERVICE_ID VARCHAR (6) UNIQUE,
DESCRIPTION VARCHAR (500),
MIN_HOURS DECIMAL (10,2),
MAX_HOURS DECIMAL (10,2),
MIN_PHOTO INT,
MAX_PHOTO INT,
BASE_PRICE DECIMAL (10,2),
ADD_ON VARCHAR (500),
SERVICE_TYPE VARCHAR (2),
FOREIGN KEY (SERVICE_TYPE) REFERENCES SERVICES(SERVICE_TYPE)
);
# Build data for PHOTOGRAPHY
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Mini', 'Studio', 'MINSTU', 'Short studio photography session for individuals or small groups', 0.5, 1, 5 , 10 , 75 , '-', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Mini', 'Lifestyle', 'MINLIF','Short photography lifestyle session for individuals, couples, small groups', 0.5, 1, 10 , 15 , 150 , '-', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Mini', 'Special Events', 'MINSPE', 'Short special event session for individuals or small groups', 2, 3, 50 , 150 , 250 , '-', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Standard', 'Studio', 'STASTU', 'Studio photography session for couples, family or groups', 2, 3, 20 , 30 , 250 , '4x6 prints / custom stickers / fridge magnets ', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Standard', 'Lifestyle', 'STALIF','Lifestyle photography session with additional time and edited images', 2, 3, 20 , 30 , 250 , '4x6 prints / custom stickers / fridge magnets ', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Standard', 'Special Events', 'STASPE', 'Special events photography session with additional time and edited images', 4, 5, 100 , 200 , 400 , '4x6 prints / custom stickers / fridge magnets ', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Premium', 'Studio', 'PRESTU', 'Extended studio photography session with more images and services', 6, 8, 30 , 80 , 700 , 'Mini Album + 4x6 prints / custom stickers / fridge magnets ', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Premium', 'Lifestyle', 'PRELIF', 'Extended lifestyle photography session with more images and services', 6, 8, 30 , 80 , 1500 , 'Album + 4x6 prints / custom stickers / fridge magnets ', 'PH');
INSERT INTO PHOTOGRAPHY (CATEGORY, NAME, SERVICE_ID, DESCRIPTION, MIN_HOURS, MAX_HOURS, MIN_PHOTO, MAX_PHOTO, BASE_PRICE, ADD_ON, SERVICE_TYPE)
VALUES ('Premium', 'Special Events', 'PRESPE', 'Extended special event photography session with more images and services', 8, 10, 300 , 500 , 3000 , 'Album + 4x6 prints / custom stickers / fridge magnets ', 'PH');
# Check PHOTOGRAPHY table
SELECT *
FROM PHOTOGRAPHY;






# Create ORDERS_DETAILS table (contains all information with regards to Sweet Pixels Studio's list of custom products offered.)
DROP TABLE IF EXISTS ORDER_DETAILS;
CREATE TABLE ORDER_DETAILS
(
    ORDER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    SERVICE_TYPE VARCHAR(2),
    SERVICE_ID VARCHAR (6),
    QNT INT,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (SERVICE_TYPE) REFERENCES SERVICES(SERVICE_TYPE)
);
# Build data for ORDER_DETAILS
INSERT INTO ORDER_DETAILS (ORDER_ID, SERVICE_TYPE, SERVICE_ID, QNT)
VALUES (1, 'PH', 'MINSTU', 1);
INSERT INTO ORDER_DETAILS (ORDER_ID, SERVICE_TYPE, SERVICE_ID, QNT)
VALUES (2, 'PH', 'MINLIF', 1);
INSERT INTO ORDER_DETAILS (ORDER_ID, SERVICE_TYPE, SERVICE_ID, QNT)
VALUES (3, 'CP', 'PAFMRD', 50);
INSERT INTO ORDER_DETAILS (ORDER_ID, SERVICE_TYPE, SERVICE_ID, QNT)
VALUES (3, 'CP', 'PAFMSQ', 50);
# Check ORDER_DETAILS table
SELECT *
FROM ORDER_DETAILS;







# QUERIES TEST

# Show list of orders with customer names
SELECT
    O.ORDER_ID,
    O.ORDER_DATE,
    C.FIRST_NAME,
    C.LAST_NAME
FROM ORDERS O
JOIN CUSTOMER C
    ON O.CUST_ID = C.CUST_ID;


# Show list of order_details with order date, booking date, service id and qnt
SELECT
    O.ORDER_ID,
    O.ORDER_DATE,
    O.BOOKING_DATE,
    OD.SERVICE_ID,
    OD.QNT
FROM ORDERS O
JOIN ORDER_DETAILS OD
    ON O.ORDER_ID = OD.ORDER_ID;
    
    
    
# Show list of orders by service ID, type, name, quantity,
# order date, booking date, and customer first and last name
# sort by booking date
SELECT
    OD.SERVICE_ID,
    P.CATEGORY,
    P.NAME,
    OD.QNT,
    O.ORDER_DATE,
    O.BOOKING_DATE,
    C.FIRST_NAME,
    C.LAST_NAME
FROM ORDER_DETAILS OD
JOIN ORDERS O
    ON OD.ORDER_ID = O.ORDER_ID
JOIN CUSTOMER C
    ON O.CUST_ID = C.CUST_ID
JOIN PHOTOGRAPHY P
    ON OD.SERVICE_ID = P.SERVICE_ID

UNION ALL

SELECT
    OD.SERVICE_ID,
    CP.CATEGORY,
    CP.NAME,
    OD.QNT,
    O.ORDER_DATE,
    O.BOOKING_DATE,
    C.FIRST_NAME,
    C.LAST_NAME
FROM ORDER_DETAILS OD
JOIN ORDERS O
    ON OD.ORDER_ID = O.ORDER_ID
JOIN CUSTOMER C
    ON O.CUST_ID = C.CUST_ID
JOIN CUSTOM_PRODUCTS CP
    ON OD.SERVICE_ID = CP.SERVICE_ID

ORDER BY BOOKING_DATE ASC;